/* ============================================================
   BuildCraft OB — Real Pairs from velas.db
   ============================================================ */

const PARES_OTC = [
  'AIG-OTC', 'AIRLINES-OTC', 'ALIBABA-OTC', 'AMAZON-OTC', 'AMZN/ALIBABA-OTC',
  'AMZN/EBAY-OTC', 'APPLE-OTC', 'ARBUSD-OTC', 'ATOMUSD-OTC', 'AUDCAD-OTC',
  'AUDCHF-OTC', 'AUDJPY-OTC', 'AUDNZD-OTC', 'AUDUSD-OTC', 'AUS200-OTC',
  'BCHUSD-OTC', 'BIDU-OTC', 'BONKUSD-OTC', 'BTCUSD-OTC-op', 'CADCHF-OTC',
  'CADJPY-OTC', 'CANNABIS-OTC', 'CARDANO-OTC', 'CASINOS-OTC', 'CHFJPY-OTC',
  'CHFNOK-OTC', 'CITI-OTC', 'COCOA-OTC', 'COFFEE-OTC', 'COKE-OTC',
  'COTTON-OTC', 'DASHUSD-OTC', 'DOTUSD-OTC', 'DYDXUSD-OTC', 'EOSUSD-OTC',
  'ETHBTC-OTC', 'ETHUSD-OTC', 'EU50-OTC', 'EURAUD-OTC', 'EURCAD-OTC',
  'EURCHF-OTC', 'EURGBP-OTC', 'EURJPY-OTC', 'EURNZD-OTC', 'EURTHB-OTC',
  'EURUSD-OTC', 'FARTCOINUSD-OTC', 'FB-OTC', 'FETUSD-OTC', 'FLOKIUSD-OTC',
  'FR40-OTC', 'FWONA-OTC', 'GALAUSD-OTC', 'GBPAUD-OTC', 'GBPCAD-OTC',
  'GBPCHF-OTC', 'GBPJPY-OTC', 'GBPNZD-OTC', 'GBPUSD-OTC', 'GER30-OTC',
  'GER30/UK100-OTC', 'GEV-OTC', 'GOOGLE-OTC', 'GOOGLE/MSFT-OTC', 'GRTUSD-OTC',
  'GS-OTC', 'HBARUSD-OTC', 'HK33-OTC', 'HYPE-OTC', 'ICPUSD-OTC',
  'IMXUSD-OTC', 'INJUSD-OTC', 'INTEL-OTC', 'INTEL/IBM-OTC', 'IOTAUSD-OTC',
  'JP225-OTC', 'JPM-OTC', 'JPYTHB-OTC', 'JUPUSD-OTC', 'KLARNA-OTC',
  'LABUBUUSD-OTC', 'LINKUSD-OTC', 'LTCUSD-OTC', 'LUNA-OTC', 'MAGNIFICENT7-OTC',
  'MANAUSD-OTC', 'MATICUSD-OTC', 'MCDON-OTC', 'MELANIAUSD-OTC', 'META/GOOGLE-OTC',
  'MORSTAN-OTC', 'MSFT-OTC', 'MSFT/AAPL-OTC', 'MU-OTC', 'NEARUSD-OTC',
  'NFLX/AMZN-OTC', 'NIKE-OTC', 'NOKJPY-OTC', 'NOTCOIN-OTC', 'NVDA-OTC',
  'NVDA/AMD-OTC', 'NZDCAD-OTC', 'NZDCHF-OTC', 'NZDJPY-OTC', 'NZDUSD-OTC',
  'ONDOUSD-OTC', 'ONYXCOINUSD-OTC', 'ORDIUSD-OTC', 'OpenAI-OTC', 'PENGUUSD-OTC',
  'PENUSD-OTC', 'PEPEUSD-OTC', 'PLTR-OTC', 'PYTHUSD-OTC', 'RAYDIUMUSD-OTC',
  'RENDERUSD-OTC', 'RONINUSD-OTC', 'SANDUSD-OTC', 'SATSUSD-OTC', 'SEIUSD-OTC',
  'SHIBUSD-OTC', 'SNAP-OTC', 'SNDK-OTC', 'SOLUSD-OTC', 'SP35-OTC',
  'SP500-OTC', 'STXUSD-OTC', 'SUGAR-OTC', 'SUIUSD-OTC', 'TAOUSD-OTC',
  'TESLA-OTC', 'TESLA/FORD-OTC', 'TIAUSD-OTC', 'TONUSD-OTC', 'TRON-OTC',
  'TRUMPUSD-OTC', 'UK100-OTC', 'UKOUSD-OTC', 'URANIUM-OTC', 'US100/JP225-OTC',
  'US2000-OTC', 'US30-OTC', 'US30/JP225-OTC', 'US500/JP225-OTC', 'USDAED-OTC',
  'USDARS-OTC', 'USDBDT-OTC', 'USDBOB-OTC', 'USDBRL-OTC', 'USDCAD-OTC',
  'USDCHF-OTC', 'USDCLP-OTC', 'USDCOP-OTC', 'USDDOP-OTC', 'USDHKD-OTC',
  'USDIDR-OTC', 'USDINR-OTC', 'USDJPY-OTC', 'USDMXN-OTC', 'USDMYR-OTC',
  'USDNGN-OTC', 'USDNOK-OTC', 'USDPHP-OTC', 'USDPLN-OTC', 'USDSAR-OTC',
  'USDSEK-OTC', 'USDSGD-OTC', 'USDTHB-OTC', 'USDTRY-OTC', 'USDVND-OTC',
  'USDZAR-OTC', 'USNDAQ100-OTC', 'USOUSD-OTC', 'WDC-OTC', 'WIFUSD-OTC',
  'WLDUSD-OTC', 'XAGUSD-OTC', 'XAU/XAG-OTC', 'XAUUSD-OTC', 'XNGUSD-OTC',
  'XPDUSD-OTC', 'XPTUSD-OTC', 'XRPUSD-OTC',
];

const PARES_OP = [
  'AIG-op', 'ALIBABA-op', 'AMAZON-op', 'APPLE-op', 'AUDCAD-op',
  'AUDCHF-op', 'AUDJPY-op', 'AUDNZD-op', 'AUDUSD-op', 'BAIDU-op',
  'BTCUSD-op', 'CADCHF-op', 'CADJPY-op', 'CHFJPY-op', 'CISCO-op',
  'CITI-op', 'COKE-op', 'ETHUSD-op', 'EURAUD-op', 'EURCAD-op',
  'EURCHF-op', 'EURGBP-op', 'EURJPY-op', 'EURNZD-op', 'EURUSD-op',
  'FACEBOOK-op', 'GBPAUD-op', 'GBPCAD-op', 'GBPCHF-op', 'GBPJPY-op',
  'GBPNZD-op', 'GBPUSD-op', 'GOOGLE-op', 'GS-op', 'INTEL-op',
  'JPM-op', 'MCDON-op', 'MORSTAN-op', 'MSFT-op', 'NIKE-op',
  'NZDCAD-op', 'NZDJPY-op', 'NZDUSD-op', 'SNAP-op', 'SpaceX-op',
  'TESLA-op', 'USDBRL-op', 'USDCAD-op', 'USDJPY-op', 'USOUSD-op',
  'XAUUSD-op', 'XRPUSD-op',
];

// Todas os pares combinados
const TODOS_OS_PARES = [...PARES_OTC, ...PARES_OP].sort();
